[package]
name = "legato-vault"
version = "0.1.5"
authors = []

[addresses]
legato_vault_addr = "ab3922ccb1794928abed8f5a5e8d9dac72fed24f88077e46593bed47dcdb7775"
aptos_framework = "0x1"
aptos_fungible_asset = "0xA"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
